name: Reusable workflow

on:
  workflow_call:
    inputs:
      value:
        description: 'Value to echo'
        required: true
        type: string

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.inputs.value }}"
